//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppForPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class InternetPrice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InternetPrice()
        {
            this.Receipt = new HashSet<Receipt>();
        }
    
        public int InternetPricesId { get; set; }
        public System.DateTime Date { get; set; }
        public int CostMinute { get; set; }
        public int PreferentialCost_at20to2_ { get; set; }
        public int PreferentialCost_at2to6_ { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipt { get; set; }
    }
}
