//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppForPractice
{
    using System;
    using System.Collections.Generic;
    
    public partial class KlientsInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public KlientsInfo()
        {
            this.Receipt = new HashSet<Receipt>();
        }
    
        public int KlientId { get; set; }
        public string ComputerNumber { get; set; }
        public string IPAddress { get; set; }
        public System.DateTime DateStart { get; set; }
        public System.TimeSpan TimeStart { get; set; }
        public System.DateTime DateEnd { get; set; }
        public System.TimeSpan TimeEnd { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Receipt> Receipt { get; set; }
    }
}
